import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { api } from '../api';

export default function CewbPrint() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [gdms, setGdms] = useState([]);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchGdm = async () => {
      try {
        const data = await api.get(`/gdms/${id}`); 
        const gdmArray = Array.isArray(data) ? data : [data];
        setGdms(gdmArray);
        setTimeout(() => {
          window.print();
        }, 500);
      } catch (err) {
        setError('Failed to load CEWB for printing.');
      }
    };
    fetchGdm();
  }, [id]);

  if (error) return <div className="p-10 text-rose-500 font-bold">{error}</div>;
  if (gdms.length === 0) return <div className="p-10 text-slate-500">Loading document...</div>;

  return (
    <div className="bg-slate-200 min-h-screen flex flex-col items-center justify-start print:bg-white print:min-h-0 print:block">
      {gdms.map((gdm, index) => {
        let totalConsignments = gdm.gcs?.length || 0;

        return (
          <div key={gdm.id} className={`w-full flex justify-center p-4 print:p-0 ${index !== gdms.length - 1 ? 'print:break-after-page mb-8 print:mb-0' : ''}`}>
            {/* Landscape A4 Layout: 297mm x 210mm */}
            <div 
              className="w-[297mm] min-h-[210mm] bg-white text-black shadow-lg print:shadow-none font-sans text-[10px] p-6 flex flex-col justify-start relative"
              style={{ boxSizing: 'border-box', fontFamily: '"Arial", "Helvetica", sans-serif' }}
            >
              {/* HEADER */}
              <div className="text-center font-bold text-sm uppercase mb-4 tracking-wider border-b border-black pb-2">
                e-Way Bill System
                <div className="text-xs tracking-normal mt-1">Consolidated E-Way Bill (Form GST EWB-02)</div>
              </div>

              <div className="flex justify-between items-start mb-6">
                <div className="flex flex-col gap-1 w-1/2">
                  <div className="flex"><span className="w-40 font-semibold">CEWB No:</span> <span className="font-bold text-sm">{gdm.cewbNumber || 'PENDING'}</span></div>
                  <div className="flex"><span className="w-40 font-semibold">CEWB Date:</span> <span>{new Date(gdm.date).toLocaleDateString('en-GB')} {gdm.time}</span></div>
                  <div className="flex"><span className="w-40 font-semibold">Generated By:</span> <span>BELL LOGISTICS</span></div>
                  <div className="flex"><span className="w-40 font-semibold">No of EWB's:</span> <span>{totalConsignments}</span></div>
                </div>
                
                <div className="flex flex-col gap-1 w-1/2">
                  <div className="flex"><span className="w-40 font-semibold">Vehicle No:</span> <span className="font-bold">{gdm.vehicle?.vehicleNumber || gdm.vehicleNumber}</span></div>
                  <div className="flex"><span className="w-40 font-semibold">From Place:</span> <span>SIVAKASI</span></div>
                  <div className="flex"><span className="w-40 font-semibold">To Place:</span> <span>{gdm.destination || 'MULTI'}</span></div>
                </div>
              </div>

              {/* TABLE */}
              <div className="flex-1 border border-black mb-4">
                <table className="w-full text-left border-collapse text-[9px]">
                  <thead>
                    <tr className="bg-gray-100 border-b border-black">
                      <th className="px-2 py-1.5 border-r border-black w-8 text-center">S.No</th>
                      <th className="px-2 py-1.5 border-r border-black w-24">EWB No</th>
                      <th className="px-2 py-1.5 border-r border-black w-20">EWB Date</th>
                      <th className="px-2 py-1.5 border-r border-black">Consignor Details</th>
                      <th className="px-2 py-1.5 border-r border-black">Consignee Details</th>
                      <th className="px-2 py-1.5 border-r border-black w-24">Dispatch From</th>
                      <th className="px-2 py-1.5 border-r border-black w-24">Ship To</th>
                      <th className="px-2 py-1.5 border-r border-black w-20 text-right">Inv. Value</th>
                    </tr>
                  </thead>
                  <tbody>
                    {gdm.gcs?.map((gc, i) => (
                      <tr key={gc.id} className="border-b border-gray-300 align-top">
                        <td className="px-2 py-1.5 border-r border-black text-center">{i + 1}</td>
                        <td className="px-2 py-1.5 border-r border-black font-semibold">{gc.ewbNumber || 'PENDING'}</td>
                        <td className="px-2 py-1.5 border-r border-black">{gc.date ? new Date(gc.date).toLocaleDateString('en-GB') : '-'}</td>
                        <td className="px-2 py-1.5 border-r border-black">
                          <div className="font-bold uppercase">{gc.consignor?.name}</div>
                          <div className="text-[8px] text-gray-600">GST: {gc.consignor?.gstin || '-'}</div>
                        </td>
                        <td className="px-2 py-1.5 border-r border-black">
                          <div className="font-bold uppercase">{gc.consignee?.name}</div>
                          <div className="text-[8px] text-gray-600">GST: {gc.consignee?.gstin || '-'}</div>
                        </td>
                        <td className="px-2 py-1.5 border-r border-black uppercase text-[8px]">
                          {gc.consignor?.city || '-'}
                        </td>
                        <td className="px-2 py-1.5 border-r border-black uppercase text-[8px]">
                          {gc.consignee?.city || '-'}
                        </td>
                        <td className="px-2 py-1.5 border-r border-black text-right font-semibold">
                          {gc.invoiceValue ? gc.invoiceValue.toFixed(2) : '-'}
                        </td>
                      </tr>
                    ))}
                    {gdm.gcs?.length === 0 && (
                      <tr>
                        <td colSpan="8" className="px-2 py-4 text-center text-gray-500">No Consignments Attached</td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>

            </div>
          </div>
        );
      })}

      {/* Action buttons (hidden on print) */}
      <button 
        onClick={() => navigate(-1)}
        className="fixed top-4 left-4 bg-slate-800 text-white px-4 py-2 rounded-lg font-bold shadow-lg print:hidden hover:bg-slate-700"
      >
        ← Back
      </button>

      <button 
        onClick={() => window.print()}
        className="fixed top-4 right-4 bg-blue-600 text-white px-4 py-2 rounded-lg font-bold shadow-lg print:hidden hover:bg-blue-500"
      >
        🖨️ Print CEWB
      </button>

    </div>
  );
}
