import React from 'react';
import { History, X } from 'lucide-react';
import { Button } from '../ui/Button';

export default function GcTrackingPanel({ selectedGc, onClose }) {
  if (!selectedGc) return null;

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-slate-900/40 backdrop-blur-sm transition-all">
      <div className="w-full max-w-md bg-white h-full shadow-2xl flex flex-col animate-in slide-in-from-right duration-300">
        {/* Panel Header */}
        <div className="p-5 border-b border-slate-100 bg-indigo-600 text-white flex justify-between items-center shrink-0">
          <div>
            <h2 className="text-xl font-black tracking-tight flex items-center gap-2"><History size={20} /> GC Tracking Log</h2>
            <p className="text-indigo-200 text-sm font-medium mt-1">Timeline for {selectedGc.gcNumber}</p>
          </div>
          <Button variant="custom" onClick={onClose} className="p-2 hover:bg-white/20 rounded-full transition-colors"><X size={20}/></Button>
        </div>
        
        <div className="p-6 bg-slate-50 border-b border-slate-200 shrink-0">
          <div className="grid grid-cols-2 gap-4">
             <div>
               <p className="text-[10px] font-bold text-slate-500 uppercase">Consignor</p>
               <p className="font-bold text-sm text-slate-800">{selectedGc.consignor?.name}</p>
             </div>
             <div>
               <p className="text-[10px] font-bold text-slate-500 uppercase">Consignee</p>
               <p className="font-bold text-sm text-slate-800">{selectedGc.consignee?.name}</p>
             </div>
             <div className="col-span-2">
               <p className="text-[10px] font-bold text-slate-500 uppercase">Current EWB Number</p>
               <p className="font-mono font-bold text-sm text-indigo-700 bg-indigo-100 px-2 py-1 rounded inline-block mt-1">{selectedGc.ewbNumber ? selectedGc.ewbNumber.replace(/(\d{4})(\d{4})(\d{4})/, '$1 $2 $3') : 'None'}</p>
             </div>
          </div>
        </div>

        {/* Timeline Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          
          {/* Original EWB Generation Event */}
          {selectedGc.ewbRawData && (
            <div className="relative pl-6 border-l-2 border-indigo-200 pb-2">
              <div className="absolute -left-[9px] top-0 w-4 h-4 bg-amber-500 border-[3px] border-white rounded-full shadow-sm"></div>
              <p className="text-xs font-bold text-amber-600 uppercase tracking-wider mb-1">{selectedGc.ewbRawData.ewayBillDate || selectedGc.ewbRawData.ewbDate || selectedGc.ewbRawData.docDate || 'Original Date'}</p>
              <p className="text-sm font-bold text-slate-800">EWB Generated By Consignor</p>
              <p className="text-xs text-slate-500 mt-1 font-medium">Original E-Way Bill <span className="font-bold text-slate-700">{selectedGc.ewbNumber}</span> created on government portal.</p>
            </div>
          )}
          
          {/* Synthetic Creation Event */}
          <div className="relative pl-6 border-l-2 border-indigo-200 pb-2">
            <div className="absolute -left-[9px] top-0 w-4 h-4 bg-indigo-500 border-[3px] border-white rounded-full shadow-sm"></div>
            <p className="text-xs font-bold text-indigo-500 uppercase tracking-wider mb-1">{new Date(selectedGc.createdAt || selectedGc.date).toLocaleString('en-IN')}</p>
            <p className="text-sm font-bold text-slate-800">GC Drafted</p>
            <p className="text-xs text-slate-500 mt-1">GC {selectedGc.gcNumber} was initiated in the system.</p>
          </div>

          {/* Database Tracking Logs */}
          {selectedGc.trackingLogs && selectedGc.trackingLogs.length > 0 && selectedGc.trackingLogs.map((log, i) => (
            <div key={i} className="relative pl-6 border-l-2 border-indigo-200 pb-2">
              <div className="absolute -left-[9px] top-0 w-4 h-4 bg-emerald-500 border-[3px] border-white rounded-full shadow-sm"></div>
              <p className="text-xs font-bold text-emerald-600 uppercase tracking-wider mb-1">{new Date(log.timestamp).toLocaleString('en-IN')}</p>
              <p className="text-sm font-bold text-slate-800">{log.actionType.replace(/_/g, ' ')}</p>
              <p className="text-xs text-slate-600 mt-1 font-medium">{log.description}</p>
              
              {log.metaData && log.metaData.fromGstin && (
                <div className="mt-2 p-2 bg-slate-100 rounded border border-slate-200 text-[10px] font-mono text-slate-600">
                  <div><span className="font-bold">EWB Value:</span> ₹{log.metaData.totInvValue}</div>
                  <div><span className="font-bold">EWB Date:</span> {log.metaData.docDate}</div>
                </div>
              )}
            </div>
          ))}

          {/* GDM Assignment */}
          {selectedGc.gdm && (
            <div className="relative pl-6 border-l-2 border-indigo-200 pb-2">
              <div className="absolute -left-[9px] top-0 w-4 h-4 bg-blue-500 border-[3px] border-white rounded-full shadow-sm"></div>
              <p className="text-xs font-bold text-blue-600 uppercase tracking-wider mb-1">{new Date(selectedGc.gdm.date || selectedGc.gdm.createdAt).toLocaleString('en-IN')}</p>
              <p className="text-sm font-bold text-slate-800">Assigned to GDM: {selectedGc.gdm.gdmNumber}</p>
              <p className="text-xs text-slate-600 mt-1 font-medium">Vehicle <span className="font-bold uppercase bg-slate-100 px-1 rounded">{selectedGc.gdm.vehicle?.vehicleNumber}</span> assigned for dispatch.</p>
            </div>
          )}

          {/* End Node */}
          <div className="relative pl-6">
            <div className="absolute -left-[9px] top-0 w-4 h-4 bg-slate-300 border-[3px] border-white rounded-full shadow-sm"></div>
            <p className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">Current State</p>
            <p className="text-sm font-bold text-slate-800">{selectedGc.status}</p>
          </div>

        </div>
      </div>
    </div>
  );
}
